spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 개별 파일 최대 크기
      max-request-size: 40MB  # 전체 요청 크기 (여러 파일 포함)

  application:
    name: variety-store-mono

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:/home/ubuntu/h2db/variety-store-mono;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

logging.level:
  org.hibernate.SQL: error
#  org.hibernate.orm.jdbc.bind: trace
#  org.springframework.security: debug

jwt:
  secret-key: "The secret length must be at least 256 bits"
  access-token-validity-millis: 7200000     # 2 * 60 * 60 * 1000 milliseconds(= 2 hours)
  refresh-token-validity-millis: 604800000  # 7 * 24 * 60 * 60 * 1000 milliseconds(= 7 days)

file:
  picture:
    directory: "/home/ubuntu/uploads/pictures/"
  pdf:
    directory: "/home/ubuntu/uploads/pdfs/"